version: '3'
services:
  api:
    container_name: flask-container
    image: kuntal0901/project:backend
    entrypoint: python3 DataQuery/app.py
    env_file:
      - .env
    ports:
      - '5000:5000'

  dataapi:
    container_name: data-container
    image: kuntal0901/project:backend
    entrypoint: python3 DataIngestion/app.py
    ports:
      - '6000:6000'

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: gourav
      POSTGRES_PASSWORD: gourav
      POSTGRES_DB: data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

  frontend:
    image: kuntal0901/project:latest
    restart: always
    ports:
      - 8000:80
    labels:
      kompose.service.type: LoadBalancer
