apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
spec:
  selector:
    matchLabels:
      app: api-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
      - name: api-backend
        command:
          - python3
          - DataQuery/app.py
        env:
            - name: CACHE_DEFAULT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: CACHE_DEFAULT_TIMEOUT
                  name: env
            - name: CACHE_REDIS_DB
              valueFrom:
                configMapKeyRef:
                  key: CACHE_REDIS_DB
                  name: env
            - name: CACHE_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: CACHE_REDIS_HOST
                  name: env
            - name: CACHE_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: CACHE_REDIS_PORT
                  name: env
            - name: CACHE_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: CACHE_REDIS_URL
                  name: env
            - name: CACHE_TYPE
              valueFrom:
                configMapKeyRef:
                  key: CACHE_TYPE
                  name: env
        image: kuntal0901/project:backend
        ports:
        - name: api-backend
          containerPort: 5000
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-backend
  labels:
    app: api-backend
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-backend

