apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataapi
spec:
  selector:
    matchLabels:
      app: dataapi
  replicas: 1
  template:
    metadata:
      labels: 
        app: dataapi
    spec:
      containers:
      - name: dataapi
        command:
          - python3
          - DataIngestion/app.py
        image: kuntal0901/project:backend
        ports:
        - name: dataapi
          containerPort: 6000
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dataapi
  labels:
    app: dataapi
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: dataapi
