apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: project-database-1
  name: project-database-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: project-database-1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/project-default: "true"
        io.kompose.service: project-database-1
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: data
            - name: POSTGRES_PASSWORD
              value: gourav
            - name: POSTGRES_USER
              value: gourav
          image: postgres
          name: project-database-1
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
