name: CI
on:
  - push
  - pull_request
  - create
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Run Postman tests
        id: postman-test
        run: |
          sleep 300
          cd $GITHUB_WORKSPACE
          newman run ./Project/Website/Backend/Testing/Backend.postman_collection.json
